/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FeedbackService } from "../feedback.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FeedbackCreateInput } from "./FeedbackCreateInput";
import { Feedback } from "./Feedback";
import { FeedbackFindManyArgs } from "./FeedbackFindManyArgs";
import { FeedbackWhereUniqueInput } from "./FeedbackWhereUniqueInput";
import { FeedbackUpdateInput } from "./FeedbackUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FeedbackControllerBase {
  constructor(
    protected readonly service: FeedbackService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Feedback })
  @nestAccessControl.UseRoles({
    resource: "Feedback",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFeedback(
    @common.Body() data: FeedbackCreateInput
  ): Promise<Feedback> {
    return await this.service.createFeedback({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,

        jobOrder: data.jobOrder
          ? {
              connect: data.jobOrder,
            }
          : undefined,
      },
      select: {
        comments: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,

        jobOrder: {
          select: {
            id: true,
          },
        },

        rating: true,
        submittedDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Feedback] })
  @ApiNestedQuery(FeedbackFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Feedback",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async feedbacks(@common.Req() request: Request): Promise<Feedback[]> {
    const args = plainToClass(FeedbackFindManyArgs, request.query);
    return this.service.feedbacks({
      ...args,
      select: {
        comments: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,

        jobOrder: {
          select: {
            id: true,
          },
        },

        rating: true,
        submittedDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Feedback })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Feedback",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async feedback(
    @common.Param() params: FeedbackWhereUniqueInput
  ): Promise<Feedback | null> {
    const result = await this.service.feedback({
      where: params,
      select: {
        comments: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,

        jobOrder: {
          select: {
            id: true,
          },
        },

        rating: true,
        submittedDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Feedback })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Feedback",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFeedback(
    @common.Param() params: FeedbackWhereUniqueInput,
    @common.Body() data: FeedbackUpdateInput
  ): Promise<Feedback | null> {
    try {
      return await this.service.updateFeedback({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,

          jobOrder: data.jobOrder
            ? {
                connect: data.jobOrder,
              }
            : undefined,
        },
        select: {
          comments: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,

          jobOrder: {
            select: {
              id: true,
            },
          },

          rating: true,
          submittedDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Feedback })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Feedback",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFeedback(
    @common.Param() params: FeedbackWhereUniqueInput
  ): Promise<Feedback | null> {
    try {
      return await this.service.deleteFeedback({
        where: params,
        select: {
          comments: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,

          jobOrder: {
            select: {
              id: true,
            },
          },

          rating: true,
          submittedDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
