/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ContractUpdateManyWithoutJobOrdersInput } from "./ContractUpdateManyWithoutJobOrdersInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { FeedbackUpdateManyWithoutJobOrdersInput } from "./FeedbackUpdateManyWithoutJobOrdersInput";
import { ProcurementUpdateManyWithoutJobOrdersInput } from "./ProcurementUpdateManyWithoutJobOrdersInput";
import { EnumJobOrderStatus } from "./EnumJobOrderStatus";

@InputType()
class JobOrderUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ContractUpdateManyWithoutJobOrdersInput,
  })
  @ValidateNested()
  @Type(() => ContractUpdateManyWithoutJobOrdersInput)
  @IsOptional()
  @Field(() => ContractUpdateManyWithoutJobOrdersInput, {
    nullable: true,
  })
  contracts?: ContractUpdateManyWithoutJobOrdersInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => CustomerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @IsOptional()
  @Field(() => CustomerWhereUniqueInput, {
    nullable: true,
  })
  customer?: CustomerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => FeedbackUpdateManyWithoutJobOrdersInput,
  })
  @ValidateNested()
  @Type(() => FeedbackUpdateManyWithoutJobOrdersInput)
  @IsOptional()
  @Field(() => FeedbackUpdateManyWithoutJobOrdersInput, {
    nullable: true,
  })
  feedbacks?: FeedbackUpdateManyWithoutJobOrdersInput;

  @ApiProperty({
    required: false,
    type: () => ProcurementUpdateManyWithoutJobOrdersInput,
  })
  @ValidateNested()
  @Type(() => ProcurementUpdateManyWithoutJobOrdersInput)
  @IsOptional()
  @Field(() => ProcurementUpdateManyWithoutJobOrdersInput, {
    nullable: true,
  })
  procurements?: ProcurementUpdateManyWithoutJobOrdersInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  scheduledDate?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumJobOrderStatus,
  })
  @IsEnum(EnumJobOrderStatus)
  @IsOptional()
  @Field(() => EnumJobOrderStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { JobOrderUpdateInput as JobOrderUpdateInput };
